spring.application.name=app
# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONEXIÓN A LA BASE DE DATOS (MySQL)
# ===============================
# Asegúrate de que el nombre de la BD coincida exactamente con tu script (gestoralmacen_db)
spring.datasource.url=jdbc:mysql://localhost:3306/gestoralmacen_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Cambia esta contraseña por la que uses en tu MySQL local (a veces es root o viene vacía)
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# 'none' es VITAL aquí porque tú ya creaste las tablas con tu propio script SQL. 
# Si pones 'update' o 'create', Hibernate podría modificar o borrar tu estructura.
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (súper útil para debugear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración del dialecto de MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Esto hará que Spring nos diga exactamente qué línea de código falla
logging.level.com.gestoralmacen.app=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG